### ISSUE TITLE
Add filter reason

### ISSUE THREAD

**Issue by Jake-Shadle** [EmbarkStudios/krates#3]
There are multiple reasons for why any particular crate won't end up in the final graph, but the filter callback only says that a crate was filtered, not why, so in complicated scenarios it can be difficult to figure that out, we should add a reason for why every crate was filtered so additional context is available to the user.

Another option, _may_ be to add an optional logging feature that logs out debug info at each decision point, but I'd rather avoid that.

**Comment by m0ssc0de** [comment]
I just looked at the whole logic of `func build_with_metadata`. It's so complicated!

I have summarized several reasons.

1. The crate is not under an acceptable `workspace`.
2. It relates to `exclude`/`PkgSpec`.
3. Its dep kind and location match `ignore_kinds`.
4. Not meeting specific needs of `target`.
5.  Double in the whole project.

If the reason is so important, could we add a map to store their `Package ID` and the reason?
